# Application bindings
$terminal = uwsm app -- $TERMINAL
$browser = omarchy-launch-browser

# Unbinds from default config
unbind = SUPER, W

unbind = SUPER, K
unbind = SUPER, J
unbind = SUPER CONTROL, S

# Window bindings
bind = SUPER, H, movefocus, l
bind = SUPER, L, movefocus, r
bind = SUPER, K, movefocus, u
bind = SUPER, J, movefocus, d

bind = SUPER, F, fullscreen
bind = SUPER CONTROL, S, exec, $terminal -e poweroff

# Overwrite existing bindings, like putting Omarchy Menu on Super + Space
# unbind = SUPER, SPACE
# bindd = SUPER, SPACE, Omarchy menu, exec, omarchy-menu
unbind = SUPER, W
bindd = SUPER, W, Browser, exec, $browser
unbind = Print

bind = SUPER, Q, killactive
bindd = SUPER, return, Terminal, exec, $terminal --working-directory="$(omarchy-cmd-terminal-cwd)"
bindd = SUPER, E, File manager, exec, $terminal -e yazi
bindd = SUPER SHIFT, B, Browser (private), exec, $browser --private
bindd = SUPER, N, Editor, exec, omarchy-launch-editor
bindd = SUPER, T, Activity, exec, $terminal -e btop
bindd = SUPER, D, Discord, exec, discord
bindd = SUPER, O, Obsidian, exec, omarchy-launch-or-focus obsidian "uwsm app -- obsidian -disable-gpu --enable-wayland-ime"

