[mgr]
show_hidden = true
linemode = "size"

[opener]
execute = [
	{ run = './$1', orphan = true }
]

[open]
append_rules = [
	{ name = "*.x86_64", use = "execute" },
]

[[plugin.prepend_previewers]]
url = "*.md"
run = 'piper -- CLICOLOR_FORCE=1 glow -w=$w -s=dark "$1"'
